export const COMPARISON_URI = "ui://subsidy-ai/comparison/v1.html";
export const COMPARISON_MIME = "text/html;profile=mcp-app";

// Self-contained resource: no CDN, external scripts, API calls or personal data storage.
export const comparisonHtml = String.raw`<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>補助金候補比較</title><style>
:root{color-scheme:light dark;font-family:system-ui,-apple-system,sans-serif;font-size:14px;background:transparent;color:light-dark(#202124,#eee)}
*{box-sizing:border-box}body{margin:0;padding:16px}h1{font-size:18px;margin:0 0 12px}.top{display:flex;gap:12px;flex-wrap:wrap;align-items:center;justify-content:space-between}select,button{font:inherit;color:inherit;background:light-dark(#fff,#292929);border:1px solid light-dark(#ccc,#666);border-radius:7px;padding:7px 10px;cursor:pointer}button:focus-visible,select:focus-visible,a:focus-visible{outline:3px solid #448aff;outline-offset:2px}.scroll{overflow:auto;max-height:650px;border:1px solid light-dark(#ddd,#555);border-radius:10px;margin-top:12px}table{border-collapse:collapse;width:100%;min-width:900px}th,td{padding:12px;text-align:left;vertical-align:top;border-bottom:1px solid light-dark(#eee,#444)}th{background:light-dark(#f6f7f8,#252525);position:sticky;top:0;z-index:1;font-size:12px}td:first-child{min-width:180px}small,.muted{color:light-dark(#62666c,#bbb)}small{display:block;margin-top:5px}.badge{display:inline-block;border-radius:5px;padding:3px 6px;background:light-dark(#f0f2f4,#353535);white-space:nowrap}.fail{color:light-dark(#a33920,#ffac94)}.detail td{background:light-dark(#fafafa,#202020)}.detail ul{padding-left:20px}.detail p{margin:8px 0}a{color:light-dark(#075bb5,#8cbbff);overflow-wrap:anywhere}.notice{font-size:12px;line-height:1.6;margin:12px 0 0}.demo{background:light-dark(#fff3c9,#514313);padding:8px;border-radius:6px;margin-bottom:12px}[hidden]{display:none!important}
</style></head><body>
<div id="demo" class="demo" hidden>デモデータ：以下はUI検証用の架空の制度・数値です。</div>
<div class="top"><h1 id="title">補助金候補比較</h1><label>並び替え <select id="sort" disabled><option value="original">会話で選んだ順</option><option value="rate">過去の採択率が高い順</option><option value="amount">補助上限が大きい順</option><option value="deadline">締切が近い順</option></select></label></div>
<p id="status" role="status" aria-live="polite">比較データを読み込んでいます…</p>
<div id="table-wrap" class="scroll" role="region" aria-label="補助金比較テーブル（横スクロール可能）" tabindex="0" hidden><table><caption class="muted">公募条件と過去の採択実績を比較</caption><thead><tr><th scope="col">制度・公募回</th><th scope="col">過去の公式採択率</th><th scope="col">補助上限</th><th scope="col">補助率</th><th scope="col">企業条件との照合</th><th scope="col">申請締切</th><th scope="col">詳細・出典</th></tr></thead><tbody id="rows"></tbody></table></div>
<p id="notice" class="notice"></p>
<script>
(()=>{
const $=id=>document.getElementById(id),labels={unconfirmed:'未確認',not_registered:'実績未登録',fetch_failed:'取得失敗'};
let data=null,expanded=new Set(),nextId=0,pending=new Map(),hostReady=false;
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);return n};
function send(method,params){window.parent.postMessage({jsonrpc:'2.0',method,params},'*')}
function resize(){if(hostReady)send('ui/notifications/size-changed',{height:Math.min(document.documentElement.scrollHeight,900),width:document.documentElement.clientWidth})}
function request(method,params){const id=++nextId;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error('接続がタイムアウトしました'))},15000);pending.set(id,{resolve,reject,timer});window.parent.postMessage({jsonrpc:'2.0',id,method,params},'*')})}
function cellText(row,key){const c=row[key];if(c.status!=='available')return labels[c.status]||'未確認';if(key==='pastRate')return c.value+'%';if(key==='maximumGrant')return Number(c.value).toLocaleString('ja-JP')+'円';if(key==='deadline')return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(c.value))+'（日本時間）'+(c.label?' '+c.label:'');return c.label}
function score(row,sort){const c=row[sort==='rate'?'pastRate':sort==='amount'?'maximumGrant':'deadline'];return c.status==='available'?(sort==='deadline'?Date.parse(c.value):c.value):null}
function draw(){if(!data)return;const tbody=$('rows');tbody.replaceChildren();const sort=$('sort').value;const rows=data.rows.map((row,i)=>({row,i}));if(sort!=='original')rows.sort((a,b)=>{const x=score(a.row,sort),y=score(b.row,sort);if(x===null)return y===null?a.i-b.i:1;if(y===null)return -1;return (sort==='deadline'?x-y:y-x)||a.i-b.i});
rows.forEach(({row,i})=>{const key=row.subsidyId+':'+row.round,tr=node('tr'),name=node('td');name.append(node('strong',row.name),node('small',row.round));tr.append(name);
for(const field of ['pastRate','maximumGrant','grantRate','fit','deadline']){const c=row[field],td=node('td');if(c.status==='available'){td.append(node('span',cellText(row,field)));if(field==='pastRate')td.append(node('small',c.round));if(field==='maximumGrant'&&c.label)td.append(node('small',c.label))}else{const badge=node('span',cellText(row,field));badge.className='badge'+(c.status==='fetch_failed'?' fail':'');td.append(badge)}tr.append(td)}
const action=node('td'),button=node('button',expanded.has(key)?'閉じる':'詳細・出典');button.type='button';button.setAttribute('aria-expanded',String(expanded.has(key)));button.setAttribute('aria-controls','detail-'+i);button.onclick=()=>{if(expanded.has(key))expanded.delete(key);else expanded.add(key);draw();const next=$('toggle-'+i);if(next)next.focus();resize()};button.id='toggle-'+i;action.append(button);tr.append(action);tbody.append(tr);
const detail=node('tr');detail.className='detail';detail.id='detail-'+i;detail.hidden=!expanded.has(key);const td=node('td');td.colSpan=7;td.append(node('strong',row.name+'：条件と根拠'));const ul=node('ul');for(const text of row.details)ul.append(node('li',text));td.append(ul);
const names={pastRate:'過去の公式採択率',maximumGrant:'補助上限',grantRate:'補助率',fit:'企業条件との照合',deadline:'申請締切'};
for(const field of Object.keys(names)){const c=row[field];td.append(node('p',names[field]+'：'+cellText(row,field)));if(field==='pastRate'&&c.status==='available')td.append(node('p',c.round+'／申請 '+c.applications+'件・採択 '+c.selected+'件'));if(c.note)td.append(node('p',c.note));for(const source of c.sources){try{const url=new URL(source.url);if(url.protocol!=='https:')continue;const p=node('p'),a=node('a',source.title);a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';p.append(a);td.append(p)}catch{}}}detail.append(td);tbody.append(detail)});resize()}
function render(value){if(!value||value.schemaVersion!=='1.0'||!Array.isArray(value.rows)||value.rows.length<1||value.rows.length>5){data=null;$('table-wrap').hidden=true;$('sort').disabled=true;$('status').textContent='比較データを表示できません。会話内のテキスト表をご確認ください。';return}try{data=value;expanded.clear();$('title').textContent=value.title;$('demo').hidden=!value.demo;$('notice').textContent=value.notice;$('sort').disabled=false;$('table-wrap').hidden=false;$('status').textContent=value.rows.length+'制度を比較しています。未確認の値は並び替えで最後に表示します。';draw()}catch{data=null;$('table-wrap').hidden=true;$('sort').disabled=true;$('status').textContent='比較データを表示できません。会話内のテキスト表をご確認ください。'}}
$('sort').onchange=()=>draw();
window.addEventListener('message',event=>{if(event.source!==window.parent)return;const message=event.data;if(!message||message.jsonrpc!=='2.0')return;if(message.id!==undefined&&pending.has(message.id)){const p=pending.get(message.id);clearTimeout(p.timer);pending.delete(message.id);if(message.error)p.reject(new Error(message.error.message));else p.resolve(message.result);return}if(message.method==='ui/notifications/tool-result'){render(message.params?.structuredContent);return}if(message.method==='ui/notifications/tool-cancelled')$('status').textContent='比較表示がキャンセルされました。';if(message.method==='ui/resource-teardown'){send('ui/notifications/resource-teardown',{});}});
request('ui/initialize',{appInfo:{name:'subsidy-comparison',version:'1.0.0'},appCapabilities:{},protocolVersion:'2026-01-26'}).then(()=>{hostReady=true;send('ui/notifications/initialized',{});resize()}).catch(()=>{if(!data)$('status').textContent='ChatGPTとの接続を確認できません。会話内のテキスト表をご確認ください。'});
})();
</script></body></html>`;
